kaban_delivery/kaban_delivery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('main.urls')),

]

kaban_delivery/main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('restaurants/', views.restaurants, name='restaurants'),
    path('restaurants/<int:restaurant_id>', views.restaurant, name='restaurant'),
    path('restaurants/<int:restaurant_id>/food', views.food, name='food'),
    path('restaurants/<int:restaurant_id>/food/<int:dish_id>', views.dish, name='dish'),
    path('restaurants/<int:restaurant_id>/drinks', views.drinks, name='drinks'),
    path('restaurants/<int:restaurant_id>/drinks/<int:drink_id>', views.drink, name='drink'),

]

kaban_delivery/users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('log_out/', views.logout_view, name='logout'),
]

kaban_delivery/main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Restaurant(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class DrinkPositions(models.Model):
    place = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField()
    price = models.FloatField()

    def __str__(self):
        print(self.name)
        return self.name


class FoodPositions(models.Model):
    place = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField()
    price = models.FloatField()

    def __str__(self):
        return self.name


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField()

    def __str__(self):
        return self.address


class Order(models.Model):
    position = models.CharField(max_length=200)
    price = models.FloatField()
    count = models.IntegerField()
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.position

kaban_delivery/users/models.py
from django.db import models

# Create your models here.

kaban_delivery/main/forms.py
from django import forms
from .models import *


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['count']
        labels = {'count': 'Количество'}

kaban_delivery/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

kaban_delivery/main/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from .forms import OrderForm
from .models import Restaurant, FoodPositions, DrinkPositions


# Create your views here.
def index(request):
    return render(request, 'main/index.html')


def restaurants(request):
    restaurants = Restaurant.objects.order_by('name')
    context = {'restaurants': restaurants}

    return render(request, 'main/restaurants.html', context)


def restaurant(request, restaurant_id):
    restaurant = Restaurant.objects.get(id=restaurant_id)

    context = {'restaurant': restaurant}

    return render(request, 'main/restaurant.html', context)


def food(request, restaurant_id):
    restaurant = Restaurant.objects.get(id=restaurant_id)

    food = restaurant.foodpositions_set.order_by('name')

    context = {'restaurant': restaurant, 'food': food}
    return render(request, 'main/food.html', context)


@login_required
def dish(request, restaurant_id, dish_id,):
    restaurant = Restaurant.objects.get(id=restaurant_id)
    dish = restaurant.foodpositions_set.get(id=dish_id)

    if request.method != 'POST':
        form = OrderForm()
    else:
        user_name = request.user
        form = OrderForm(data=request.POST)

        new_order = form.save(commit=False)
        new_order.position = dish.name
        new_order.price = dish.price
        new_order.buyer = request.user.id
        form.save()

        return redirect('main:restaurant', restaurant_id)

    context = {'dish': dish, 'form': form}

    return render(request, 'main/dish.html', context)


@login_required
def drink(request, restaurant_id, drink_id,):
    restaurant = Restaurant.objects.get(id=restaurant_id)
    drink = restaurant.drinkpositions_set.get(id=drink_id)

    if request.method != 'POST':
        form = OrderForm()
    else:
        form = OrderForm(data=request.POST)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.position = drink.name
            new_order.price = drink.price
            if new_order.count < 0:
                new_order.count = 0
            new_order.buyer = request.user
            form.save()

            return redirect('main:restaurant', restaurant_id)

    context = {'drink': drink, 'form': form}

    return render(request, 'main/drink.html', context)


def drinks(request, restaurant_id):
    restaurant = Restaurant.objects.get(id=restaurant_id)
    drinks = restaurant.drinkpositions_set.order_by('name')

    context = {'restaurant': restaurant, 'drinks': drinks}
    return render(request, 'main/drinks.html', context)

kaban_delivery/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from .forms import UserRegisterForm


# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserRegisterForm()
    else:
        form = UserRegisterForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('main:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)


def logout_view(request):
    logout(request)
    return redirect('/')

kaban_delivery/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <a href="{% url 'main:index' %}">Главная</a>-
    <a href="{% url 'main:restaurants' %}">Рестораны</a>-
    <a href="">Корзина</a>-
    {% if user.is_authenticated %}
        <span><strong>Здравствуйте, {{ user.username }}!</strong></span>
        <a href="{% url 'users:logout' %}">Выйти</a>
    {% else %}
        <a href="{% url 'users:register' %}">Регистрация</a>-
        <a href="{% url 'users:login' %}">Войти</a>
    {% endif %}
    {% block content %}{% endblock %}
</body>
</html>

kaban_delivery/main/templates/main/dish.html
{% extends 'main/base.html' %}

{% block title %}{{dish}}{% endblock %}

{% block content %}

    <h1>{{dish}}</h1>
    <h2>{{dish.price}}</h2>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">В корзину</button>

    </form>

{% endblock %}

kaban_delivery/main/templates/main/drink.html
{% extends 'main/base.html' %}

{% block title %}{{ drink }}{% endblock %}

{% block content %}
    <h1>{{drink}}</h1>
    <h2>{{drink.price}}</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">В корзину</button>
    </form>
{% endblock %}

kaban_delivery/main/templates/main/drinks.html
{% extends 'main/base.html' %}

{% block title %}{{restaurant}} Напитки{% endblock %}

{% block content %}
    <ul>
        {% for drink in drinks %}
            <li>
                <a href="{% url 'main:drink' restaurant.id drink.id %}">{{drink}}</a>
            </li>
        {% empty %}
            <li>Пока что нет напитков, доступных для заказа</li>
        {% endfor %}
    </ul>
{% endblock %}

kaban_delivery/main/templates/main/food.html
{% extends 'main/base.html' %}

{% block title %}{{restaurant}} еда{% endblock %}

{% block content %}
    <ul>
        {% for pos in food %}
            <li>
                <a href="{% url 'main:dish' restaurant.id pos.id %}">
                    <h3>
                        {{pos}}
                    </h3>
                </a>
            </li>
        {% empty %}
            <li>
                <h3>
                    Пока что нет блюд, доступных для заказа!
                </h3>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

kaban_delivery/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
    <h1>Главная</h1>
{% endblock %}

kaban_delivery/main/templates/main/restaurant.html
{% extends 'main/base.html' %}

{% block title %}{{restaurant}}{% endblock %}

{% block content %}
    <p>
        <h1>{{restaurant}}</h1>
    </p>
    <a href="{% url 'main:food' restaurant.id %}">Еда</a>-
    <a href="{% url 'main:drinks' restaurant.id %}">Напитки</a>
{% endblock %}

kaban_delivery/main/templates/main/restaurants.html
{% extends 'main/base.html' %}

{% block title %}Рестораны{% endblock %}


{% block content %}
    <ul>
        {% for restaurant in restaurants %}
            <li>
                <a href="{% url 'main:restaurant' restaurant.id %}">{{ restaurant }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}